// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWG8dFngKFNOIePGs3ETAlAPeMVryTuTU',
    appId: '1:613877748599:web:9ee4c0e5c6f4fe00a90772',
    messagingSenderId: '613877748599',
    projectId: 'flutterauth-c307d',
    authDomain: 'flutterauth-c307d.firebaseapp.com',
    storageBucket: 'flutterauth-c307d.appspot.com',
    measurementId: 'G-LJ35WL478G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdWI9wprAD3tPbIFFoLu4qpfMS92GV3ck',
    appId: '1:613877748599:android:f01f0c91c1e90a7ca90772',
    messagingSenderId: '613877748599',
    projectId: 'flutterauth-c307d',
    storageBucket: 'flutterauth-c307d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFiKpmgBZEUU9auquPQiLP-bVLsuK5_as',
    appId: '1:613877748599:ios:80fa6add324789c5a90772',
    messagingSenderId: '613877748599',
    projectId: 'flutterauth-c307d',
    storageBucket: 'flutterauth-c307d.appspot.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFiKpmgBZEUU9auquPQiLP-bVLsuK5_as',
    appId: '1:613877748599:ios:80fa6add324789c5a90772',
    messagingSenderId: '613877748599',
    projectId: 'flutterauth-c307d',
    storageBucket: 'flutterauth-c307d.appspot.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWG8dFngKFNOIePGs3ETAlAPeMVryTuTU',
    appId: '1:613877748599:web:c6517918fbe7b791a90772',
    messagingSenderId: '613877748599',
    projectId: 'flutterauth-c307d',
    authDomain: 'flutterauth-c307d.firebaseapp.com',
    storageBucket: 'flutterauth-c307d.appspot.com',
    measurementId: 'G-6LX9HYVT3B',
  );
}
